### ISSUE TITLE
TypeError: Cannot read property 'id_token' of undefined

### ISSUE THREAD

**Issue by TheodoraPetkova** [solid/solid#202]
Hi everyone! I am starting my Solid journey and will try to upload data to it from the G+ platform. I created my account some months ago, but these days I am getting this error message, has anyone encountered the same thing?
Any help is appreciated!

cardOutline.expand: Unable to fetch <https://teodora.solid.community/profile/card>: Failed to load  <https://teodora.solid.community/profile/card> Fetcher: fetch failed: TypeError: Cannot read property 'id_token' of undefined status: 999
--

**Comment by RubenVerborgh** [comment]
Yes, your localStorage contains old data. Could you try clearing it?

**Comment by TheodoraPetkova** [comment]
Thank you for a prompt reply! I am afraid I don't know how to do this. Is there a link where I can read more?

**Comment by RubenVerborgh** [comment]
If you can bring up the inspector window and write localStorage.clear() in the console, it should be fixed. If not, a private window will do the trick.

**Comment by TheodoraPetkova** [comment]
Ok. Tried this. Nothing happened. Maybe this is just not the console you are referring to. 
![screen shot 2018-10-11 at 10 45 41 am](https://user-images.githubusercontent.com/40993908/46788533-f82c7980-cd42-11e8-882e-006f6c6655cc.png)

**Comment by megoth** [comment]
You need to call `localStorage.clear`, i.e. write `localStorage.clear()` ^_^

**Comment by TheodoraPetkova** [comment]
You are right. It works in a private (incognito mode) window. Does this have to do with the annoying prompts here: 
![screen shot 2018-10-11 at 8 49 12 am](https://user-images.githubusercontent.com/40993908/46788651-42155f80-cd43-11e8-89ff-a45bdaf18ca7.png)

**Comment by TheodoraPetkova** [comment]
Arne, thanks! Tried that one first, but didn't work and I decided to get rid of the (). [sorry, I know it is probably painful to read me :) but I am very illiterate re: code]
![screen shot 2018-10-11 at 10 49 52 am](https://user-images.githubusercontent.com/40993908/46788814-ac2e0480-cd43-11e8-84df-58c81656d66e.png)

**Comment by TheodoraPetkova** [comment]
@RubenVerborgh thank you! Now it is working even in not a private window, and I managed to add people. 
![screen shot 2018-10-11 at 11 05 31 am](https://user-images.githubusercontent.com/40993908/46789639-9c172480-cd45-11e8-97bc-27037567469a.png)

**Comment by kjetilk** [comment]
Great that you fixed it, @TheodoraPetkova ! This is a very special bug only for those who have been with us for a while, sorry about that! The problem here was that the browser kept stuff around, so even as we fixed on our end, everyone who had been with us for a while had to go through that problem. Fortunately, it hasn't affected new users.

**Comment by melvincarvalho** [comment]
> this is a very special bug only for those who have been with us for a while

I run into this bug almost every day.

**Comment by TheodoraPetkova** [comment]
@kjetilk and @melvincarvalho thank you for letting me know! I feel special :)) Using the opportunity that you are around I have some questions from different paradigms. Shooting them:
1. Isn't it best, if you have a website, to create a WebID on your website (I tried btw :) but failed)
2. The POD - could that be again on your own server or droplet
3. Please don't laugh - when is this going to become more UX friendly (like the screenshot here for example: https://images.fastcompany.net/image/upload/w_596,c_limit,q_auto:best,f_auto/wp-cms/uploads/2018/09/A-look-under-the-hood-at-a-Solid-data-browser-and-app.png) and can I help with something here? (e.g. digging kidehen's webID and then dragging it into the target felt strange)
4. Are we (I mean you as builders and me as a strange enthusiast user) building a skeleton now?And looking into how these loosely joined data bits can read-write each other? Is this the purpose of the actions now - just test and see what work and what doesn't. 
Thanks again for paying attention. Much appreciated!

**Comment by RubenVerborgh** [comment]
@melvincarvalho 

> I run into this bug almost every day.

Then you have (directly or indirectly) multiple versions of solid-auth-client running on the same host. Please upgrade them all to the latest version (which will warn you if you are in that situation).

**Comment by kezike** [comment]
@RubenVerborgh @melvincarvalho @kjetilk I also still get this message to this day despite how long I have been using this platform and despite clearing `localStorage`. I'm also not getting a warning that I am using multiple versions of `solid-auth-client` (I know because I have seen this warning in the past). Is there some. Are there any other culprits for this issue other than multiple cached versions of `solid-auth-client`?

**Comment by RubenVerborgh** [comment]
@kezike Can you confirm this still happens with solid-auth-client@2.2.14?
If so, it is likely a new issue with the same symptom (since the old issue has definitely been fixed). If the problem persists, please create a new issue with exact steps to reproduce and a stack trace. Thanks!

**Comment by RubenVerborgh** [comment]
The problem @kezike had was because he was using an old version of popup.html, which contains an old version of solid-auth-client. So this confirms that all `id_token` error messages are due to old versions of solid-auth-client.

Always use the latest popup, preferably by using the `solid-auth-client` module and linking to `node_modules/solid-auth-client/dist-popup/popup.html`.

**Comment by kezike** [comment]
Yes Ruben, you are absolutely right! As I have mentioned in response to https://github.com/kezike/solid-pg/issues/1, my problem is that I had run `solid-auth-client generate-popup` so long ago with an older version of `solid-auth-client` and was reusing the output of this for all of my projects. This is a learning moment for me to avoid careless reuse moving forward. Thanks!
